worlds:
  world:
    day: 1
    season: SPRING
    weather: BEAUTIFUL

# Days that must go by before the world moves to the next season
Days-Per-Season: 30
# Whether to activate the effects of the seasonal weathers
Custom-Weathers: true
# How many seconds per damage dealt to a player on a harmful weather
Seconds-Of-Damage: 3